# render.yaml
services:
  - type: web
    name: flowpay-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        fromDatabase:
          name: flowpay-db
          property: connectionString